// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnzh0_1UZBva6bfr_TlYNK2MDSEqA8Uk8',
    appId: '1:958623060295:android:36c17f31198f70f6df7c62',
    messagingSenderId: '958623060295',
    projectId: 'basketorders-9a569',
    storageBucket: 'basketorders-9a569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvCNyLrlly4w9CEGmCmcm6YuC-z8Lnko',
    appId: '1:958623060295:ios:50b1d9c8375d9244df7c62',
    messagingSenderId: '958623060295',
    projectId: 'basketorders-9a569',
    storageBucket: 'basketorders-9a569.firebasestorage.app',
    iosBundleId: 'com.example.basketorders',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyVN50rBKEd0CMMKidbmxdv3Lb5fPM4Gg',
    appId: '1:958623060295:web:25de95ddee3a3af6df7c62',
    messagingSenderId: '958623060295',
    projectId: 'basketorders-9a569',
    authDomain: 'basketorders-9a569.firebaseapp.com',
    storageBucket: 'basketorders-9a569.firebasestorage.app',
  );

}